version: '3'

services:
  app:
    # network host
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lion_app
    container_name: lion-app
    volumes:
      - .:/app:z
      - staticfiles:/var/www/html/static/
    env_file:
      - ./.envs/.django
    ports:
      - '8000:8000'
    # command: /start
    # networks:
    #   - app-network

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    image: lion_nginx
    container_name: nginx
    restart: always
    ports:
      - '8888:80'
    depends_on:
      - app
    volumes:
      - staticfiles:/var/www/html/static/
    # networks:
    #   - app-network

    # networks:
    #   app-network:

volumes:
  staticfiles:
