name: lesson1

on:
    workflow_dispatch:

jobs:
    echo-event:
        name: echo event
        runs-on: ubuntu-latest
        steps:
            - name: get event
              run: echo "This event is ${{github.event_name}}"

    call-workflow:
        strategy:
            matrix:
                person: ['Eunsub', 'ssamko', 'lion']
        uses: ./.github/workflows/lesson2.yml
        with:
            person: ${{ matrix.person }}
        
