name: "reusable workflow"

on:
    workflow_call:

jobs:
    reuse:
        name: reuse
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: echo "resusable workflow"
              