name: "reusable workflow"

on:
    workflow_call:
        inputs:
            person:
                required: true
                type: string

jobs:
    reuse:
        name: reuse
        runs-on: ubuntu-latest
        steps:
            - name: greeting
              run: echo "Hi, ${{ inputs.person }}"
