name: lesson1

on:
    push:
    pull_request:

jobs:
    echo-event:
        name: echo event
        runs-on: ubuntu-latest
        steps:
            - name: get event
              run: echo "This event is ${{github.event_name}}"

    cloning:
        name: git clone
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: list files
              run: ls -al
            - name: docker build
              working-directory: ./
              run: |
                docker build --tag lion-app .
            - name: docker images
              run: docker images lion-app
