name: lesson1

on:
    workflow_dispatch:

jobs:
    echo-event:
        name: echo event
        runs-on: ubuntu-latest
        steps:
            - name: get event
              run: echo "This event is ${{github.event_name}}"

    call-workflow:
        uses: teacherSsamko/django_sample_for_development_lesson/.github/workflows/lesson2.yml@main
        
